apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      serviceAccountName: {{ .Values.app.name }}
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
          ports:
            - containerPort: {{ .Values.app.port }}
          {{- with .Values.app.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- toYaml .Values.app.env | nindent 12 }}
          envFrom:
            - secretRef:
                name: app-secrets       # ESO 가 병합 생성
          readinessProbe:
            httpGet:
              path: {{ .Values.app.health }}
              port: {{ .Values.app.port }}
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.app.health }}
              port: {{ .Values.app.port }}
            initialDelaySeconds: 90
            periodSeconds: 15
