# 앱 파드용 SA (IRSA: 앱 S3 권한 등)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.app.roleArn }}
