apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: farmily-app
  namespace: farmily-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: farmily-app
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60 # 평균 CPU 60%
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 300 # 줄일 땐 5분 천천히 (트래픽 출렁임을 흡수)