apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: farmily-app
  namespace: farmily-prod
  annotations:
    # LBC CRD(elbv2.k8s.aws)가 아직 없을 때 dry-run 으로 전체 sync 막히는 것 방지.
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  serviceRef: { name: farmily-app, port: 8080 }
  targetGroupARN: arn:aws:elasticloadbalancing:ap-northeast-2:851957594139:targetgroup/prod-eks-tg/49fea87ed8029421
  targetType: ip
