# 앱 네임스페이스
apiVersion: v1
kind: Namespace
metadata: { name: farmily-dev }
---
# ESO가 Secrets Manager를 읽을 때 쓸 Service Account (IRSA)
# 이 SA를 AWS에 연결함
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-reader
  namespace: farmily-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::851957594139:role/dev-eks-eso-reader-role
---
# AWS secret manager 해서 받아온 SA로 인증하고, 시크릿의 모든 키를 가져옴
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata: 
  name: aws-sm
  namespace: farmily-dev
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: eso-reader
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: farmily-dev
spec:
  #1시간 마다 재동기화 (rotate 방지)
  refreshInterval: 1h
  #aws sm이라는 통로를 사용한다.
  secretStoreRef: { name: aws-sm, kind: SecretStore }
  target:
    # farmily/dev/app의 모든 키를 app-secrets이라는 k8s secret으로 만들어라
    name: app-secrets # 생성될 k8s secret 이름
  dataFrom:
    - extract: {key: farmily/dev/app} # 이 시크릿의 모든 키를 통째로
    - extract: {key: farmily/dev/app-infra} # DB 유저네임, 레디스 호스트 등등 키