apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: farmily-app
  namespace: farmily-dev
spec:
  serviceRef: { name: farmily-app, port: 8080 }
  targetGroupARN: arn:aws:elasticloadbalancing:ap-northeast-2:851957594139:targetgroup/dev-eks-tg/f94ef7701a2bda39
  targetType: ip